include:
 - project: 'World/Phosh/meta-phosh'
   ref: '38648e8c4caeea0293e1a724fc171875f6b591e5'
   file: '/ci/phosh-common-jobs.yml'
 - project: 'Infrastructure/freedesktop-ci-templates'
   ref: 'd03cddbcff35f26861429fc816c00323f48e99af'
   file: '/templates/ci-fairy.yml'

stages:
 - build
 - test
 - style-checks

default:
  # Protect CI infra from rogue jobs
  timeout: 15 minutes
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  # For ci-fairy
  FDO_UPSTREAM_REPO: World/Phosh/phosh-mobile-settings
  DEBIAN_IMAGE: $CI_REGISTRY/world/phosh/phosh-mobile-settings/debian:v0.0.2026-01-01
  COMMON_BUILD_OPTS: --werror -Db_coverage=true
  GCHECK_DIRS: src tests plugins
  PHOC: dbus-launch phoc --no-xwayland
  WLR_BACKENDS: headless

.forky_vars: &forky_vars
  variables:
    DIST: forky
    BUILD_OPTS:  ${COMMON_BUILD_OPTS}

.build_step: &build_step
  script:
    - 'echo "Build opts: ${BUILD_OPTS}"'
    - meson setup ${BUILD_OPTS} . _build
    - meson compile -C _build

.test_step: &test_step
  script:
    - !reference [.phosh-prepare-apt]
    - XDG_RUNTIME_DIR=$PWD ${PHOC} -E "meson test --print-errorlogs -C _build"
    - ninja -C _build coverage-html || true

.before: &before
  before_script:
    - !reference [.phosh-prepare-apt]
    - apt-get -y update
    - apt-get -y build-dep .

# Sanity checks of MR settings and commit logs
sanity:
  extends:
    - .fdo.ci-fairy
  stage: style-checks
  variables:
    GIT_DEPTH: "100"
  needs: []
  script: |
    ci-fairy check-commits --signed-off-by --junit-xml=commit-message-junit-report.xml
  artifacts:
    reports:
      junit: commit-message-junit-report.xml
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'

build:native-debian-forky:
  stage: build
  image: ${DEBIAN_IMAGE}
  <<: *before
  <<: *forky_vars
  <<: *build_step
  artifacts:
    paths:
      - _build

test:native-debian-forky:
  stage: test
  image: ${DEBIAN_IMAGE}
  needs:
    - build:native-debian-forky
  <<: *before
  <<: *forky_vars
  <<: *test_step
  coverage: '/^lines:\s+([\d.]+\%)\s+/'
  artifacts:
    when: always
    reports:
      junit: _build/meson-logs/testlog.junit.xml

asan-test-native-debian-forky:
  stage: test
  image: ${DEBIAN_IMAGE}
  tags: [asan]
  needs: []
  <<: *before
  script:
    - meson setup -Db_sanitize=address -Dtweaks-data-dir=tests/data _build-asan
    - XDG_RUNTIME_DIR=$PWD ${PHOC} -E "meson test --print-errorlogs -C _build-asan"
  allow_failure: true
  artifacts:
    paths:
      - _build-asan

asan-app-native-debian-forky:
  stage: test
  image: ${DEBIAN_IMAGE}
  variables:
    PMS_BUS_NAME: mobi.phosh.MobileSettings
  tags: [asan]
  needs: ['asan-test-native-debian-forky']
  <<: *before
  script: |
    set -e
    # Make sure everything is built
    meson compile -C _build-asan
    # `run` enables all debugging when G_MESSAGES_DEBUG is unset
    export G_MESSAGES_DEBUG=doesnotmatter
    # Make ASAN output useful
    export LSAN_OPTIONS=suppressions=$PWD/data/leak-suppress.txt
    export ASAN_OPTIONS=fast_unwind_on_malloc=0
    # No a11y
    export GTK_A11Y=none
    # CI has no DRM devices
    export GSK_RENDERER=cairo

    set -x
    export XDG_RUNTIME_DIR="$(mktemp -d)"
    eval $(dbus-launch --sh-syntax)
    phoc --no-xwayland -E $PWD/_build-asan/run &
    PMS_PID=$!
    echo "pid is $PMS_PID, waiting for bus name"
    gdbus wait --timeout 20 --session "${PMS_BUS_NAME}"
    sleep 1
    echo "Found ${PMS_BUS_NAME}, killing process"
    kill -TERM "${PMS_PID}"
    wait "${PMS_PID}"
  allow_failure: true

check-po:
  stage: test
  extends: .phosh-check-po

check-consistency:
  stage: test
  extends: .phosh-check-consistency

format-check:
  stage: style-checks
  extends: .phosh-format-check
  allow_failure: true

check-g-style:
  stage: style-checks
  allow_failure: true
  script:
    - ./.gitlab-ci/g-style ${GCHECK_DIRS}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "**/*.c"
          - "**/*.h"

check-meson:
  stage: style-checks
  extends:
    - .phosh-check-meson

check-markdown:
  stage: style-checks
  variables:
    PHOSH_MARKDOWN_PATHS: "*.md src/conf-tweaks/*.md"
  extends: .phosh-check-markdown
